travis:
  secure:
    BINSTAR_TOKEN: dML8w9sIw8qKC5v7k4CmCYcDZnTFVyu615iJWz6BcqTqoqE1O6qH2an4CgGrzKQMukokFfXXkE9DnqWkCIusH7TsjXkNvCtyD83DNCTfNBR6n+kEifrOEpjIGeKkUJDER195/YxELoTGgoPsmRA87oOJ+YypiAJoTTDQ5eEKIHk7EsFJxEbwGGyneaMqdhuni/ntLzMsM/jzpcMrAsdNe0pFEY9bYxqHxwrpfs7uirljcLQbaqOZ23rFkXtefk+bZKLupRThBbDtBTz2wTXSsVEirCWkYhInHLrY5H8RBsib/8hZP9u85KKXYPk27y1X9ayKuK2tJHP2l/Cu+Q/L4erdl2aeOgTJhcoYQtnCac9IY0xBPkJXqJ/Asl44BmofNCVlRHbIj+kcwqBclX2sR1cgvvcNEZnYQxvObWArQdr/lM2jxGKuS1zGImdM1KpkZmWb+b4uowmhOPgUef5Gt/Pv1wSVopLBYihcohXtHtHqJZS47DC7n/sW+tVJIrFAPyIDiV8JVnGQLARVa0Xizwzh6qQeQFC3z8TF7f1lAQtrXP1Gq4G9zVNYvYtbUVKesFbt13L2GY3iSCEs7KLwhzYDzXASmqDnCYM0cXIAhnsj4YPgGu7bgM6sUen0/gRTn8RTpByt1zm4zzWkb5x5oa4Id4iD8pUTfJi+H5LTOs8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
